name: Build and deploy Next.js SSR app to Azure Web App - demo-sak-nextjs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build
          mkdir -p deploy
          cp -r .next/standalone/* deploy/
          mkdir -p deploy/.next
          cp -r .next/static deploy/.next/static
          if [ -d public ]; then cp -r public deploy/public; fi

      - name: Zip deployment package
        run: |
          cd deploy
          zip -r ../nextjs.zip .
          cd ..

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: nextjs.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: package
          path: .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B55AC48E08774076AB0184F4E58AC1E4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A3B9A1EDF2B14DBFA636FAD1FB4A1892 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_888BE5BFA27C4206AF49B3A83EA6E8F5 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'demo-sak-nextjs'
          package: nextjs.zip
